tap "homebrew/bundle"
tap "homebrew/services"

# General
brew "anyenv"
brew "awscli"
brew "glib"
brew "curl"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "iperf"
brew "jq"
brew "mas"
brew "mycli"
brew "peco"
brew "pgcli"
brew "rename"
brew "ssh-copy-id"
brew "streamlink"
brew "telnet"
brew "wget"
cask "alt-tab"
cask "appcleaner"
cask "caffeine"
cask "google-chrome"
cask "google-japanese-ime"
cask "miro"
cask "postman"
cask "skitch"
cask "steermouse"
cask "swiftdefaultappsprefpane"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
mas "1Password 7", id: 1333542190
mas "CotEditor", id: 1024640650
mas "Magnet", id: 441258766
mas "QR Journal", id: 483820530
mas "The Unarchiver", id: 425424353
mas "Tot", id: 1491071483
mas "WinArchiver Lite", id: 414855915
vscode "42Crunch.vscode-openapi"
vscode "bierner.markdown-mermaid"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "jakebathman.mysql-syntax"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "redhat.vscode-yaml"
vscode "unifiedjs.vscode-mdx"
vscode "xabikos.JavaScriptSnippets"
